# Generated by the protocol buffer compiler.  DO NOT EDIT!
# source: cameraStatus.proto

import sys
_b=sys.version_info[0]<3 and (lambda x:x) or (lambda x:x.encode('latin1'))
from google.protobuf import descriptor as _descriptor
from google.protobuf import message as _message
from google.protobuf import reflection as _reflection
from google.protobuf import symbol_database as _symbol_database
# @@protoc_insertion_point(imports)

_sym_db = _symbol_database.Default()




DESCRIPTOR = _descriptor.FileDescriptor(
  name='cameraStatus.proto',
  package='mmind',
  syntax='proto3',
  serialized_options=None,
  serialized_pb=_b('\n\x12\x63\x61meraStatus.proto\x12\x05mmind\"\x8f\x01\n\x0c\x43\x61meraStatus\x12\n\n\x02ip\x18\x01 \x01(\t\x12\x0f\n\x07version\x18\x02 \x01(\t\x12\x10\n\x08serialId\x18\x03 \x03(\t\x12\r\n\x05\x65yeId\x18\x04 \x01(\t\x12\x12\n\ncameraType\x18\x05 \x01(\x05\x12\x0e\n\x06\x63ommit\x18\x06 \x01(\t\x12\x0c\n\x04temp\x18\x07 \x01(\x01\x12\x0f\n\x07isLinux\x18\x08 \x01(\x08\x62\x06proto3')
)




_CAMERASTATUS = _descriptor.Descriptor(
  name='CameraStatus',
  full_name='mmind.CameraStatus',
  filename=None,
  file=DESCRIPTOR,
  containing_type=None,
  fields=[
    _descriptor.FieldDescriptor(
      name='ip', full_name='mmind.CameraStatus.ip', index=0,
      number=1, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='version', full_name='mmind.CameraStatus.version', index=1,
      number=2, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='serialId', full_name='mmind.CameraStatus.serialId', index=2,
      number=3, type=9, cpp_type=9, label=3,
      has_default_value=False, default_value=[],
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='eyeId', full_name='mmind.CameraStatus.eyeId', index=3,
      number=4, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='cameraType', full_name='mmind.CameraStatus.cameraType', index=4,
      number=5, type=5, cpp_type=1, label=1,
      has_default_value=False, default_value=0,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='commit', full_name='mmind.CameraStatus.commit', index=5,
      number=6, type=9, cpp_type=9, label=1,
      has_default_value=False, default_value=_b("").decode('utf-8'),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='temp', full_name='mmind.CameraStatus.temp', index=6,
      number=7, type=1, cpp_type=5, label=1,
      has_default_value=False, default_value=float(0),
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
    _descriptor.FieldDescriptor(
      name='isLinux', full_name='mmind.CameraStatus.isLinux', index=7,
      number=8, type=8, cpp_type=7, label=1,
      has_default_value=False, default_value=False,
      message_type=None, enum_type=None, containing_type=None,
      is_extension=False, extension_scope=None,
      serialized_options=None, file=DESCRIPTOR),
  ],
  extensions=[
  ],
  nested_types=[],
  enum_types=[
  ],
  serialized_options=None,
  is_extendable=False,
  syntax='proto3',
  extension_ranges=[],
  oneofs=[
  ],
  serialized_start=30,
  serialized_end=173,
)

DESCRIPTOR.message_types_by_name['CameraStatus'] = _CAMERASTATUS
_sym_db.RegisterFileDescriptor(DESCRIPTOR)

CameraStatus = _reflection.GeneratedProtocolMessageType('CameraStatus', (_message.Message,), dict(
  DESCRIPTOR = _CAMERASTATUS,
  __module__ = 'cameraStatus_pb2'
  # @@protoc_insertion_point(class_scope:mmind.CameraStatus)
  ))
_sym_db.RegisterMessage(CameraStatus)


# @@protoc_insertion_point(module_scope)
